spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://vigneshmysqlserver123.mysql.database.azure.com:3306/javaapp?useSSL=true&requireSSL=true ##Here javaapp is the database name

spring.datasource.username=mysqladmin

spring.datasource.password=Mysql@123456
