name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  gitleaks:
    name: Secret Detection
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          GITLEAKS_VERSION="8.30.0"

          curl -sSfL \
            "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" \
            -o gitleaks.tar.gz

          tar -xzf gitleaks.tar.gz gitleaks

          sudo mv gitleaks /usr/local/bin/gitleaks

          gitleaks version

      - name: Run Gitleaks
        id: gitleaks
        run: |
          set +e

          gitleaks git . --redact --verbose

          EXIT_CODE=$?

          echo "Gitleaks exit code: $EXIT_CODE"

          if [ "$EXIT_CODE" -eq 0 ]; then
            echo "✅ No secrets detected"
          elif [ "$EXIT_CODE" -eq 1 ]; then
            echo "❌ Secrets detected!"
          else
            echo "❌ Gitleaks encountered an error"
          fi

          echo "exit_code=$EXIT_CODE" >> "$GITHUB_OUTPUT"

          exit "$EXIT_CODE"

      # - name: Upload Gitleaks Report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: gitleaks-report
      #     path: gitleaks-report.json
